# Generated by Django 5.0.1 on 2024-02-08 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsecretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.DateTimeField()),
                ('hora_final', models.DateTimeField()),
                ('horas_total', models.FloatField(null=True)),
                ('actividad', models.CharField(max_length=255)),
                ('autorizacion', models.BooleanField(default=False, null=True)),
                ('observacion', models.CharField(max_length=255, null=True)),
                ('evidencia', models.FileField(null=True, upload_to='archivos_pdf/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
