# Generated by Django 5.0.1 on 2024-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subsecretaria_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeacion',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pdf/'),
        ),
    ]
