# Generated by Django 5.0.1 on 2024-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_planeacion_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='archivos_pdf/'),
        ),
    ]
